### ISSUE TITLE
PlotSquared v6

### ISSUE THREAD

**Issue by Oskicz** [hraponssi/InputCooldown#1]
Can you please make a version without need of PlotSquared v6 plugin? I need that so i will get cooldown for lever on Survival server where players keep autoclicking on it making huge redstone lags i will be thankful

Or maybe you know other plugin like this?

**Comment by hraponssi** [comment]
I'm not sure if there are other plugins with similar functionality. Having the plugin work without plotsquared was something I wanted to have originally, but ended up skipping. I'll look into it again when I have some free time.

**Comment by hraponssi** [comment]
I did the work for this in March with 5efada3, but didn't get to do any testing for it. It's still untested, but the latest version 1.1.5 should have basic functionality without plotsquared installed. In cases where plotsquared can't be used for permissions the plugin will require admin mode instead.
